# Generated by Django 3.2.12 on 2022-06-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
    ]
